In [1]:
import pandas as pd

In [2]:
pd

In [3]:
data = pd.read_csv("renewable-energy-stock-account-2007-2020-csv.csv")

In [5]:
print(data.head(5))

   year resource        variable           units   magnitude  \
0  2007   Biogas   Closing stock         Dollars   Thousands
1  2007   Biogas      Generation  Gigawatt hours      Actual
2  2007   Biogas  Gigawatt hours          Number  Proportion
3  2007   Biogas   Opening stock         Dollars   Thousands
4  2007   Biogas   Other changes         Dollars   Thousands

                   source  data_value flag
0  Environmental Accounts    86656.00    R
1                    MBIE      224.00    F
2                    MBIE        0.01    F
3  Environmental Accounts         NaN    F
4  Environmental Accounts         NaN    F

In [6]:
print(data.columns)

Index(['year', 'resource', 'variable', 'units', 'magnitude', 'source',
       'data_value', 'flag'],
      dtype='object')

In [9]:
print(data.resource)

0      Biogas
1      Biogas
2      Biogas
3      Biogas
4      Biogas
        ...
694      Wood
695      Wood
696      Wood
697      Wood
698      Wood
Name: resource, Length: 699, dtype: object

In [11]:
for index,row in data.iterrows():
    print(row.resource)

Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood
Biogas
Biogas
Biogas
Biogas
Biogas
Biogas
Coal
Gas
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Geothermal
Hydro
Hydro
Hydro
Hydro
Hydro
Hydro
Oil
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Renewable
Solar
Solar
Solar
Solar
Solar
Solar
Total generation
Total generation
Waste heat
Wind
Wind
Wind
Wind
Wind
Wind
Wood
Wood
Wood
Wood
Wood
Wood

In [12]:
data.loc[data.resource =="Hydro"]

,year,resource,variable,units,magnitude,source,data_value,flag
14,2007,Hydro,Closing stock,Dollars,Thousands,Environmental Accounts,9380001.00,R
15,2007,Hydro,Generation,Gigawatt hours,Actual,MBIE,24249.00,F
16,2007,Hydro,Gigawatt hours,Number,Proportion,MBIE,0.58,F
17,2007,Hydro,Opening stock,Dollars,Thousands,Environmental Accounts,NaN,F
18,2007,Hydro,Other changes,Dollars,Thousands,Environmental Accounts,NaN,F
...,...,...,...,...,...,...,...,...
665,2020,Hydro,Generation,Gigawatt hours,Actual,MBIE,25440.00,P
666,2020,Hydro,Gigawatt hours,Number,Proportion,MBIE,0.58,P
667,2020,Hydro,Opening stock,Dollars,Thousands,Environmental Accounts,9991647.00,P
668,2020,Hydro,Other changes,Dollars,Thousands,Environmental Accounts,2095787.00,P
669,2020,Hydro,Resource rent,Dollars,Thousands,Environmental Accounts,725246.00,P

In [13]:
data.describe()

              year    data_value
count   699.000000  6.850000e+02
mean   2013.490701  1.099322e+06
std       4.029385  3.114252e+06
min    2007.000000 -3.111777e+06
25%    2010.000000  4.700000e+01
50%    2013.000000  8.316000e+03
75%    2017.000000  2.184000e+05
max    2020.000000  1.714458e+07

In [14]:
data.sort_values('resource')

,year,resource,variable,units,magnitude,source,data_value,flag
0,2007,Biogas,Closing stock,Dollars,Thousands,Environmental Accounts,86656.00,R
105,2009,Biogas,Resource rent,Dollars,Thousands,Environmental Accounts,5136.00,F
104,2009,Biogas,Other changes,Dollars,Thousands,Environmental Accounts,1692.00,R
103,2009,Biogas,Opening stock,Dollars,Thousands,Environmental Accounts,83903.00,R
102,2009,Biogas,Gigawatt hours,Number,Proportion,MBIE,0.00,F
...,...,...,...,...,...,...,...,...
445,2015,Wood,Generation,Gigawatt hours,Actual,MBIE,349.00,F
446,2015,Wood,Gigawatt hours,Number,Proportion,MBIE,0.01,F
447,2015,Wood,Opening stock,Dollars,Thousands,Environmental Accounts,166511.00,R
299,2012,Wood,Resource rent,Dollars,Thousands,Environmental Accounts,8834.00,R
698,2020,Wood,Resource rent,Dollars,Thousands,Environmental Accounts,9036.00,P

In [17]:
data.groupby('resource').mean()

                         year    data_value
resource
Biogas            2013.500000  3.151812e+04
Coal              2013.500000  2.422786e+03
Gas               2013.500000  7.630143e+03
Geothermal        2013.500000  8.431096e+05
Hydro             2013.500000  3.319291e+06
Oil               2013.500000  1.257143e+01
Renewable         2013.500000  3.842671e+06
Solar             2013.500000  4.851793e+03
Total generation  2013.341463  3.683222e+05
Waste heat        2013.500000  4.985714e+01
Wind              2013.500000  2.538718e+05
Wood              2013.500000  4.609427e+04